controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/JointGroupPositionController

arm_controller:
  ros__parameters:
    joints:
      - joint1_base_rotate
      - joint2_shoulder
      - joint3_elbow
      - joint4_forearm
      - joint5_wrist
      - joint6_gripper_mount
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    joints:
      - joint_jaw1
      - joint_jaw2   # commands must mirror jaw1: send [x, -x]
